### PR TITLE
DOC: GEFS example

### LINKED ISSUE #37: add Aaron's tweet example to docs
I added a minor tweak here to use cfVarName which matches the name of the returned DataArray.

```
url = "simplecache::https://www.ncei.noaa.gov/thredds/catalog/model-gefs-003/202008/20200831/catalog.xml"
intake.open_thredds_merged(
    url,
    path=["NCEP gens-a Grid 3 Member-Forecast *-372 for 2020-08-31 00:00*"],
    driver="netcdf",
    concat_kwargs={"dim": "member"},
    xarray_kwargs=dict(
        engine="cfgrib",
        backend_kwargs=dict(
            filter_by_keys={"typeOfLevel": "heightAboveGround", "cfVarName": "t2m"}
        ),
    ),
).to_dask()
```

### PR DESCRIPTION
**Pull request by raybellwaves**
Closes #37

### CODE REVIEW

**Comment by andersy005** [comment]
Thank you for putting this together, @raybellwaves! To fix the linting issue, could you enable `pre-commit`

**Comment by aaronspring** [comment]
Advanced example with cfgrib?

**Comment by aaronspring** [comment]
I think Anderson meant a ## subheading. 

### Multi-file concat_kwargs cfgrib 

under ## caching

**Review by aaronspring — APPROVED** [review]

**Comment by aaronspring** [comment]
I now realise that my example wasn’t that super good. Only one dimension concationated. Wouldn’t actually require concat_kwargs IMO. 

path = "NCEP gens-a Grid 3 Member-Forecast *-3* for 2020-08-31 00:00*" (haven’t tried)

could maybe concat 21 number and a few steps.

**Comment by raybellwaves** [comment]
> I now realise that my example wasn’t that super good. Only one dimension concationated. Wouldn’t actually require concat_kwargs IMO.
> 
> path = "NCEP gens-a Grid 3 Member-Forecast _-3_ for 2020-08-31 00:00*" (haven’t tried)
> 
> could maybe concat 21 number and a few steps.

multi-dim concat is probably out of the scope here.

Been a while since I looked at that (https://stackoverflow.com/questions/47545138/python-xarray-open-mfdataset-concat-along-two-dimensions ; https://stackoverflow.com/questions/51487206/combining-spatial-netcdf-files-using-xarray-python/59377471#59377471)

@andersy005 this good to go?

**Review by andersy005 — APPROVED** [review]
This looks great, @raybellwaves! The CI failures are unrelated. Merging this shortly

**Pull request merged**
