### PR TITLE
options for combine_by_coords

### PR DESCRIPTION
**Pull request by aaronspring**

### CODE REVIEW

**Comment by aaronspring** [comment]
Sometimes like in my Linked PR the attrs differ. Any better solution @andersy005 ?

**Comment by aaronspring** [comment]
Mind looking over this @andersy005 ?

**Review by andersy005 — APPROVED** [review]
Thank you for your patience, @aaronspring! This looks good to me 👍


Side note: would you be interested in helping out with maintaining this project? :)

**Comment by aaronspring** [comment]
Yep, I can help

**Pull request merged**
